# Redis credentials
# IMPORTANT: Change the password before deploying to production!
#
# To create with a custom password:
#   oc create secret generic redis-credentials \
#     --from-literal=REDIS_PASSWORD="your-secure-password" \
#     -n $NAMESPACE --dry-run=client -o yaml | oc apply -f -
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: advanced-rag
type: Opaque
stringData:
  # Default development password - CHANGE FOR PRODUCTION
  REDIS_PASSWORD: "changeme-in-production"
  # Connection URL for applications (same-namespace access)
  REDIS_URL: "redis://:changeme-in-production@redis:6379/0"
