# Persistent Volume Claim for Meilisearch data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data
  labels:
    app: meilisearch
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/part-of: advanced-rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # Adjust size based on expected index size
      # Meilisearch stores indexes on disk
      storage: 10Gi
  # storageClassName: gp3  # Uncomment and adjust for your cluster
